{{- if and .Values.edgeApi.enabled .Values.edgeApi.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.edgeApi.tokenSecretName }}
type: Opaque
data:
  token: {{ .Values.edgeApi.token | b64enc }}
{{- end }}
