{{- if .Values.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airbridge.fullname" . }}-flower
spec:
  replicas: {{ .Values.flower.replicas }}
  selector:
    matchLabels:
      app: {{ include "airbridge.fullname" . }}-flower
  template:
    metadata:
      labels:
        app: {{ include "airbridge.fullname" . }}-flower
    spec:
      containers:
      - name: flower
        image: "{{ .Values.flower.image }}:{{ .Values.flower.tag }}"
        imagePullPolicy: {{ .Values.flower.pullPolicy }}
        args: ["flower"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: {{ .Values.airflow.executor | quote }}
        - name: AIRFLOW__API__EDGE__ENABLED
          value: {{ .Values.edgeApi.enabled | quote }}
{{- if .Values.edgeApi.tokenSecretName }}
        - name: EDGE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.edgeApi.tokenSecretName }}
              key: token
{{- end }}
{{- if .Values.edgeApi.tokenSecretId }}
        - name: EDGE_API_TOKEN_ID
          value: {{ .Values.edgeApi.tokenSecretId | quote }}
{{- end }}
        ports:
        - containerPort: {{ .Values.flower.service.port }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.flower.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.flower.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: airflow-config
          mountPath: /opt/airflow/airflow.cfg
          subPath: airflow.cfg
      volumes:
      - name: airflow-config
        configMap:
          name: {{ include "airbridge.fullname" . }}-config
{{- end }}
