{{- if and .Values.flower.enabled .Values.flower.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "airbridge.fullname" . }}-flower
spec:
  minAvailable: {{ .Values.flower.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "airbridge.fullname" . }}-flower
{{- end }}
