apiVersion: v1
kind: Service
metadata:
  name: {{ include "airbridge.fullname" . }}-postgres
spec:
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
  selector:
    app: {{ include "airbridge.fullname" . }}-postgres
