apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airbridge.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "airbridge.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "airbridge.fullname" . }}-postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"
        imagePullPolicy: {{ .Values.postgres.pullPolicy }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db | quote }}
        ports:
        - containerPort: {{ int .Values.postgres.port }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        emptyDir: {}
