{{- if and .Values.simpleAuth.enabled .Values.simpleAuth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.simpleAuth.passwordsSecret.name }}
type: Opaque
stringData:
  {{ .Values.simpleAuth.passwordsSecret.key }}: |
    { "{{ .Values.simpleAuth.adminUser }}": "{{ .Values.simpleAuth.adminPassword }}" }
{{- end }}

