apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airbridge.fullname" . }}-triggerer
spec:
  replicas: {{ .Values.triggerer.replicas }}
  selector:
    matchLabels:
      app: {{ include "airbridge.fullname" . }}-triggerer
  template:
    metadata:
      labels:
        app: {{ include "airbridge.fullname" . }}-triggerer
    spec:
      containers:
      - name: triggerer
        image: "{{ .Values.triggerer.image }}:{{ .Values.triggerer.tag }}"
        imagePullPolicy: {{ .Values.triggerer.pullPolicy }}
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: {{ .Values.airflow.executor | quote }}
        - name: AIRFLOW__API__EDGE__ENABLED
          value: {{ .Values.edgeApi.enabled | quote }}
        - name: EDGE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.edgeApi.tokenSecretName }}
              key: token
        livenessProbe:
          exec:
            command: ["bash", "-c", "airflow jobs check triggerer"]
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          exec:
            command: ["bash", "-c", "airflow jobs check triggerer"]
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: airflow-config
          mountPath: /opt/airflow/airflow.cfg
          subPath: airflow.cfg
{{- if .Values.dags.persistence.enabled }}
        - name: dags
          mountPath: {{ .Values.dags.path }}
{{- end }}
      volumes:
      - name: airflow-config
        configMap:
          name: {{ include "airbridge.fullname" . }}-config
{{- if .Values.dags.persistence.enabled }}
      - name: dags
        persistentVolumeClaim:
          claimName: {{ include "airbridge.fullname" . }}-dags
{{- end }}
