apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airbridge.fullname" . }}-webserver
spec:
  replicas: {{ .Values.webserver.replicas }}
  selector:
    matchLabels:
      app: {{ include "airbridge.fullname" . }}-webserver
  template:
    metadata:
      labels:
        app: {{ include "airbridge.fullname" . }}-webserver
    spec:
      containers:
      - name: webserver
        image: "{{ .Values.webserver.image }}:{{ .Values.webserver.tag }}"
        imagePullPolicy: {{ .Values.webserver.pullPolicy }}
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: {{ .Values.airflow.executor | quote }}
        - name: AIRFLOW__API__EDGE__ENABLED
          value: {{ .Values.edgeApi.enabled | quote }}
{{- if .Values.edgeApi.tokenSecretName }}
        - name: EDGE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.edgeApi.tokenSecretName }}
              key: token
{{- end }}
{{- if .Values.edgeApi.tokenSecretId }}
        - name: EDGE_API_TOKEN_ID
          value: {{ .Values.edgeApi.tokenSecretId | quote }}
{{- end }}
        ports:
        - containerPort: {{ .Values.webserver.service.port }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.webserver.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.webserver.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: airflow-config
          mountPath: /opt/airflow/airflow.cfg
          subPath: airflow.cfg
{{- if .Values.dags.persistence.enabled }}
        - name: dags
          mountPath: {{ .Values.dags.path }}
{{- end }}
{{- if and .Values.dagSync.enabled (eq .Values.dagSync.mode "sidecar") }}
{{ include "airbridge.dagSync.container" . | indent 6 }}
{{- end }}
      volumes:
      - name: airflow-config
        configMap:
          name: {{ include "airbridge.fullname" . }}-config
{{- if .Values.dags.persistence.enabled }}
      - name: dags
        persistentVolumeClaim:
          claimName: {{ include "airbridge.fullname" . }}-dags
{{- end }}
