{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "airbridge.fullname" . }}-webserver
  annotations:
    {{- if eq .Values.ingress.controller "nginx" }}
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.ipAllowList }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .Values.ingress.ipAllowList | quote }}
    {{- end }}
    {{- if .Values.ingress.rateLimit.rps }}
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.ingress.rateLimit.rps }}"
    {{- end }}
    {{- if .Values.ingress.rateLimit.burst }}
    nginx.ingress.kubernetes.io/limit-burst: "{{ .Values.ingress.rateLimit.burst }}"
    {{- end }}
    {{- if .Values.ingress.waf.enabled }}
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    {{- end }}
    {{- if .Values.ingress.healthCheckPath }}
    nginx.ingress.kubernetes.io/health-check-path: {{ .Values.ingress.healthCheckPath | quote }}
    {{- end }}
    {{- else if eq .Values.ingress.controller "gke" }}
    kubernetes.io/ingress.class: gce
    {{- if .Values.ingress.waf.securityPolicy }}
    networking.gke.io/security-policy: {{ .Values.ingress.waf.securityPolicy | quote }}
    {{- end }}
    {{- if .Values.ingress.healthCheckPath }}
    ingress.gcp.kubernetes.io/healthcheck-path: {{ .Values.ingress.healthCheckPath | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.ingress.tls.acmCertificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.tls.acmCertificateArn | quote }}
    {{- end }}
    {{- if .Values.ingress.tls.issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "airbridge.fullname" . }}-webserver
                port:
                  number: {{ .Values.webserver.service.port }}
{{- end }}
