# Values tuned for local kind or minikube cluster
webserver:
  image: airbridge-webserver
  tag: "3.0.4"
  pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 8080
    type: ClusterIP
scheduler:
  image: airbridge-scheduler
  tag: "3.0.4"
  pullPolicy: IfNotPresent
  replicas: 1
triggerer:
  image: airbridge-triggerer
  tag: "3.0.4"
  pullPolicy: IfNotPresent
  replicas: 1
flower:
  enabled: false
  image: apache/airflow
  tag: "2.7.1"
  pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 5555
    type: ClusterIP
edgeApi:
  enabled: true
  tokenSecretName: edge-api-token
  tokenSecretId: ""
  createSecret: false
  token: ""

ingress:
  enabled: true
  controller: nginx
  host: airbridge.localhost
  healthCheckPath: /
  tls:
    enabled: false

dags:
  path: /opt/airflow/dags
  persistence:
    enabled: false
    # size: 5Gi
    # storageClassName: standard
    # accessMode: ReadWriteMany
  gitSync:
    enabled: false

dagSync:
  enabled: false
  bucket: ""
  prefix: ""
  image: amazon/aws-cli:2.13.5
  mode: cronjob   # cronjob or sidecar
  schedule: "*/1 * * * *"
  intervalSeconds: 60
  backoffLimit: 3
  retries: 5

airflow:
  # executor: LocalExecutor
  executor: airflow.providers.edge3.executors.EdgeExecutor
  config: |
    [core]
    load_examples = False
    [logging]
    remote_logging = True
    remote_log_conn_id = aws_default
    remote_base_log_folder = s3://airbridge-logs/logs
    delete_local_logs = True
    [api_auth]
    backend = airflow.api_fastapi.auth.backend.default.allow_all
    jwt_secret = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlZGdlLXdvcmtlciIsImlhdCI6MTc1NTYzNTExNywibmJmIjoxNzU1NjM1MTEyLCJleHAiOjE3NTU2Mzg3MTcsImF1ZCI6InVybjphaXJmbG93LmFwYWNoZS5vcmc6dGFzayJ9.X4wUOu26SxckgkmmnytT_BYzYUernXmKw6Vy-cfkTak
    [edge]
    api_enabled = True
    api_url = http://localhost:8080/edge_worker/v1/rpcapi

  

postgres:
  image: postgres
  tag: "15"
  pullPolicy: IfNotPresent
  user: airflow
  password: airflow
  db: airflow
  port: 5432
