webserver:
  image: airbridge-webserver
  tag: "3.0.4"
  pullPolicy: IfNotPresent
  service:
    port: 8080
scheduler:
  image: airbridge-scheduler
  tag: "3.0.4"
  pullPolicy: IfNotPresent
triggerer:
  image: airbridge-triggerer
  tag: "3.0.4"
  pullPolicy: IfNotPresent

edgeApi:
  enabled: true
  tokenSecretName: edge-api-token

dags:
  path: /opt/airflow/dags
  persistence:
    enabled: true
    size: 5Gi
    # Use an RWX class if multiple pods may run on different nodes.
    # Common examples:
    #  - EKS:  efs-sc
    #  - AKS:  azurefile-csi
    #  - GKE:  filestore-csi
    storageClassName: standard 
    accessMode: ReadWriteMany   # If your class only supports RWO, change to ReadWriteOnce

  # If you prefer pulling DAGs from git, enable this instead of (or in addition to) manual uploads.
  gitSync:
    enabled: false   