# Values tuned for local kind or minikube cluster
webserver:
  image: airbridge-webserver
  tag: "3.0.4"
  pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 8080
    type: ClusterIP
scheduler:
  image: airbridge-scheduler
  tag: "3.0.4"
  pullPolicy: IfNotPresent
  replicas: 1
triggerer:
  image: airbridge-triggerer
  tag: "3.0.4"
  pullPolicy: IfNotPresent
  replicas: 1
flower:
  enabled: true
  image: apache/airflow
  tag: "2.7.1"
  pullPolicy: IfNotPresent
  replicas: 1
  service:
    port: 5555
    type: ClusterIP
edgeApi:
  enabled: true
  tokenSecretName: edge-api-token

dags:
  path: /opt/airflow/dags
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: standard
    accessMode: ReadWriteMany
  gitSync:
    enabled: false

airflow:
  executor: airflow.providers.edge3.executors.EdgeExecutor
  config: |
    [core]
    load_examples = False
