webserver:
  replicas: 2
  service:
    type: ClusterIP
scheduler:
  replicas: 2
triggerer:
  replicas: 2
flower:
  enabled: false

ingress:
  enabled: true
  controller: gke
  host: airbridge.stage.example.com
  tls:
    enabled: true
    secretName: stage-cert

dagSync:
  enabled: false
  bucket: ""
  prefix: ""
  image: amazon/aws-cli:2.13.5
  mode: cronjob
  schedule: "*/1 * * * *"
  intervalSeconds: 60
  backoffLimit: 3
  retries: 5
