webserver:
  image: airbridge-webserver
  tag: "3.0.4"
  pullPolicy: IfNotPresent
  service:
    port: 8080
scheduler:
  image: airbridge-scheduler
  tag: "3.0.4"
  pullPolicy: IfNotPresent
triggerer:
  image: airbridge-triggerer
  tag: "3.0.4"
  pullPolicy: IfNotPresent

edgeApi:
  enabled: true
  tokenSecretName: edge-api-token
